#
# requires .env file with
# - LOCAL_ADDRESS : the ip address of the docker host

version: '2.1'
services:

  docker-discovery:
    image: dcache/docker-discovery-agent
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

  zk:
    image: zookeeper:3.5

  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zk
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=${LOCAL_ADDRESS}
    - KAFKA_CREATE_TOPICS=iostat:1:1,ioerr:1:1
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181/kafka
    - LOG4J_LOGGER_KAFKA=WARN
    - LOG4J_LOGGER_ORG_APACHE_KAFKA=WARN
    - LOG4J_LOGGER_ORG_APACHE_ZOOKEEPER=WARN

    links:
    - zk:zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  hz:
    image: hazelcast/hazelcast
    environment:
    - JAVA_OPTS=-Dhazelcast.config=/hazelcast.xml
    volumes:
    - "./hazelcast.xml:/hazelcast.xml"

  mds:
    image: dcache/pnfs-community
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
    - hz
    - zk
    environment:
    - JAVA_OPT=
    - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    - ZOOKEEPER_CONNECT=zk:2181
    command: mds
    links:
    - hz:hz-host
    ports:
    - "2049:2049"
    volumes:
    - ./exports:/pnfs/etc/exports
    - ./mds.xml:/pnfs/etc/svc.xml
    - ./nfs.properties:/pnfs/etc/nfs.properties
    - ./chimera.properties:/pnfs/etc/chimera.properties
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"

  ds:
    image: dcache/pnfs-community
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    depends_on:
    - hz
    - zk
    - mds
    - docker-discovery
    environment:
    - LOCALADDRESS=${LOCAL_ADDRESS}
    - JAVA_OPT=
    - ZOOKEEPER_CONNECT=zk:2181
    command: ds
    links:
    - hz:hz-host
    - docker-discovery:dockerhost
    ports:
    - "2052"
    volumes:
    - ./ds.xml:/pnfs/etc/svc.xml
    - ./ds.properties:/pnfs/etc/ds.properties
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"
